### ISSUE TITLE
[FEAT] Cache Github endpoint responses

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/RADAR-Appserver#249]
**Is your feature request related to a problem? Please describe.**
Following #247, it would be good to cache Github responses to improve response times, avoid the rate limits, and reduce unnecessary repeated calls.

**Describe the solution you'd like**
As suggested by @blootsvoets and @yatharthranjan, we can use the `CachedMap` impl and an `ExpiringMap` implementation for this. Also, taking into account the maximum memory usage.

**Describe alternatives you've considered**
`Hazelcast` for caching.

**Priority**
5

**Difficulty**
6

**Additional context**
Supports #247

**Comment by yatharthranjan** [comment]
other alternatives:

- `Spring Cache`: then we can use `CacheManager` to evict values (on memory limits). Spring Cache annotations are also compatible completely with `Hazelcast` so no migration needed if we move to `hazelcast` in the future. See more [here](https://www.baeldung.com/spring-boot-evict-cache).

**Comment by yatharthranjan** [comment]
@mpgxvii is this fixed with #432 ?

**Comment by mpgxvii** [comment]
Fixed in #432
