### ISSUE TITLE
[BUG] Token key endpoints skipped on fail

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/RADAR-Appserver#369]
Please check if the bug has already been reported in the Issues Tab and mention any related issues here.

**Describe the bug**
In the `radar_is.yml` config file, multiple Management Portal public key endpoints can be set for token validation. However, when the app server fails to reach one of the endpoints on the list, the rest of the list is skipped.

**Priority**
3

**Difficulty**
5

**Expected behavior**
The app server should continue to try the fetch the rest of the public keys on the list even if some fail.

**Comment by yatharthranjan** [comment]
I believe this is part of the radar-auth library from management portal. It will need to be updated there (possibly in [TokenValidator](https://github.com/RADAR-base/ManagementPortal/blob/master/radar-auth/src/main/java/org/radarbase/auth/authentication/TokenValidator.java))

**Comment by mpgxvii** [comment]
Fixed in #423 and in new MP2.0 radar-auth in #449
