### ISSUE TITLE
[FEAT] Separate Notification Add and Schedule Workflows

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Appserver#41]
**Is your feature request related to a problem? Please describe.**
Currently, when any notification **add** endpoint is used, it automatically schedules the notifications. This is not ideal as other use cases may need different functionality. Also to ensure separation of concerns and single responsibility principle. Moreover, add endpoint can be confusing if it is also scheduling.

**Describe the solution you'd like**
These should be separated out and a parameter specified to schedule the requests when adding them. Moreover, a separate endpoint should be provided if want to schedule the notifications later. The following paths need to be added -

```
# To schedule a single notification
POST /projects/{projectId}/users/{subjectId}/notifications/{notificationId}/schedule
```

```
# To schedule a all notifications for the user
POST /projects/{projectId}/users/{subjectId}/notifications/schedule
```

```
# To schedule when adding batch notifications
POST  /projects/{projectId}/users/{subjectId}/notifications/batch?schedule=true
```

```
# To schedule when adding a single notifications
POST  /projects/{projectId}/users/{subjectId}/notifications?schedule=true
```

**Describe alternatives you've considered**
NA

**Priority**
4

**Difficulty**
5

**Additional context**

**Comment by Hsankesara** [comment]
Hi @yatharthranjan, I can work on this issue. It would help me to know Appserver better.

**Comment by yatharthranjan** [comment]
hi @Hsankesara, sure. This is based on the Spring boot framework, so if you don't know about it, a read to it's intro would be good. I can give a detailed overview of the Appserver in our meeting on Monday.

**Comment by Hsankesara** [comment]
Sounds, Great. I will look into spring boot framework meanwhile.
