### ISSUE TITLE
Add security using Management Portal

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Appserver#6]
Add this app-server as a resource in MP and add security here like the [Rest-Api](https://github.com/RADAR-base/RADAR-RestApi) does

**Comment by yatharthranjan** [comment]
Or perhaps on second thoughts maybe some alternative so as to not tightly couple the server with Management Portal

**Comment by blootsvoets** [comment]
FYI: for example the Gateway abstracts away from management portal by allowing multiple implementations for authentication: https://github.com/RADAR-base/RADAR-Gateway/blob/master/src/main/kotlin/org/radarcns/gateway/auth/Auth.kt. Although permission names are taken from MP, you can as well implement a mapping for another authorization provider. Implementations:
- https://github.com/RADAR-base/RADAR-Gateway/blob/master/src/main/kotlin/org/radarcns/gateway/auth/ManagementPortalAuth.kt
- https://github.com/RADAR-base/RADAR-Gateway/blob/master/src/main/kotlin/org/radarcns/gateway/auth/JwtAuth.kt

**Comment by yatharthranjan** [comment]
Ok great, Thanks. Is there a standard for the permission names so that other OAuth providers can also be used by just implementing the Auth interface (for example, without changing the annotations)?

**Comment by blootsvoets** [comment]
Yes, most providers allow setting the scope. The scope name is `<Entity>.<Operation>.`, for example, `PROJECT.READ`, `SUBJECT.UPDATE`, `MEASUREMENT.CREATE`. For a full list, see https://github.com/RADAR-base/ManagementPortal/blob/dev/radar-auth/src/main/java/org/radarcns/auth/authorization/Permission.java

**Comment by yatharthranjan** [comment]
okay. Thanks

**Comment by yatharthranjan** [comment]
Closed by #27
