### ISSUE TITLE
[FEAT] Schedule generation

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Appserver#70]
**Is your feature request related to a problem? Please describe.**
Currently, the schedule is generated in the app. It would be better to centralise this in the appserver. Also enables easy investigation of the schedule when there are problems

**Describe the solution you'd like**
The appserver should generate the schedule on request (and also as a request parameter on creation of a new user) for a user using their enrolment date and the protocols (already present in appserver using github). Will need another endpoint for this.

**Describe alternatives you've considered**
Scheduling in the app but that makes the app lose the schedule once someone uninstalls the app and gives no insight.

**Priority**
4

**Difficulty**
5

**Additional context**
We can use the same logic for scheduling used in the app here -- https://github.com/RADAR-base/RADAR-Questionnaire/blob/5422e2973854111630590c20c1ac6e702c85b265/src/app/core/services/schedule/schedule-generator.service.ts#L34

**Comment by mpgxvii** [comment]
Initial implementation at #85

**Comment by mpgxvii** [comment]
Specific features/components:
1. Generalise/abstract out protocol handling to handle different types of protocol: 
- Simple Protocol for the regular protocol with offsets
- Random Protocol for randomised questionnaire times with the given boundaries (See https://github.com/RADAR-base/RADAR-Questionnaire/issues/691)

**Comment by yatharthranjan** [comment]
@mpgxvii i assume this complete now. Shall we close?
